language: go

go:
  - 1.11.x

notifications:
  email: false

git:
  depth: 1

env:
  - GO111MODULE=on

script:
  # todo have golangci-lint here in the lint make target instead of metalinter
  - if [ -n "$(go fmt ./...)" ]; then exit 1; fi
  - make all

after_success:
  - bash <(curl -s https://codecov.io/bash)
